# División Survey: cobertura nacional. Revisar con MARIMAR antes de publicar.
# Solo datos generales y verificables; sin tarifas ni plazos exactos.

SURVEY = {
 'es': dict(
   path='/servicios/survey/', crumb='División Survey',
   title='Survey marítimo e inspección de carga en Venezuela | MARIMAR C.A.',
   desc='División Survey de MARIMAR C.A.: inspección de vehículos, carga, contenedores, draft survey, on/off-hire y condición de buques en todos los puertos de Venezuela. Informes independientes para seguros y reclamos.',
   kicker='División Survey · Toda Venezuela', h1='Inspecciones marítimas y de carga en todos los puertos de Venezuela',
   lead='Verificamos de forma independiente el estado de buques, cargas y vehículos en origen y destino. Donde esté su carga, allí inspeccionamos: entregamos evidencia técnica confiable para operaciones, seguros y reclamos.',
   svc_t='Qué inspeccionamos',
   services=[('Vehículos', 'Registro por VIN al embarque y a la descarga: daños, faltantes, accesorios y protocolo fotográfico estandarizado.'),
             ('Carga general y de proyecto', 'Condición, cantidad y daños. Supervisión de carga, descarga, estiba y trincaje.'),
             ('Contenedores', 'Condición del contenedor, precintos, consolidado y desconsolidado.'),
             ('Draft survey', 'Determinación de la carga embarcada o descargada por lectura de calados.'),
             ('On-hire / off-hire', 'Condición del buque y combustible a bordo al inicio y al término de un arriendo.'),
             ('Condición de buques y daños', 'Inspección de buques y embarcaciones, e informes de daños para aseguradoras y reclamos.')],
   how_t='Cómo trabajamos',
   steps=[('Solicitud', 'Indíquenos el tipo de inspección, el puerto, la carga y la fecha estimada.'),
          ('Inspección en sitio', 'Nuestro inspector registra la condición con un protocolo fotográfico y un checklist estandarizados.'),
          ('Informe independiente', 'Recibe un informe técnico con evidencia, útil para su operación, su aseguradora o su reclamo.')],
   ports_t='Puertos donde inspeccionamos',
   ports_lead='Cubrimos los puertos y terminales de Venezuela. Si su operación es en un puerto que no aparece en la lista, escríbanos y coordinamos la inspección.',
   why_t='Por qué un survey independiente',
   why=[('Evidencia que se sostiene', 'Un registro hecho por un tercero, con fecha y fotos, pesa más ante la naviera, el puerto o la aseguradora.'),
        ('Origen y destino', 'Comparar el estado al embarque y a la descarga permite atribuir el daño al tramo donde ocurrió.'),
        ('Rapidez', 'Los reclamos tienen plazos cortos: por eso inspeccionamos antes de que la carga salga del recinto portuario.')],
   faq=[['¿Inspeccionan en cualquier puerto de Venezuela?', 'Sí. La División Survey cubre los puertos y terminales del país. Coordinamos el traslado del inspector según la fecha de la operación.'],
        ['¿Por qué conviene inspeccionar también en origen?', 'Si solo se inspecciona en destino, el informe acredita cómo llegó la carga, pero no dónde se dañó. Con el registro de origen se puede atribuir el daño al tramo de transporte.'],
        ['¿El informe sirve para reclamar al seguro?', 'Sí. Es un informe técnico independiente, con registro fotográfico y descripción de daños, pensado para seguros y reclamos.'],
        ['¿Con cuánta anticipación debo solicitarlo?', 'Lo antes posible, idealmente al conocer la fecha de embarque o de arribo, para asegurar la presencia del inspector.']],
   cta='Solicitar inspección', wa='Hola, necesito una inspección (survey). Tipo: … Puerto: … Carga: … Fecha: …',
   nav='Survey', view='Ver puerto', survey_in='Survey en'),
 'en': dict(
   path='/en/services/marine-survey/', crumb='Survey Division',
   title='Marine Surveys & Cargo Inspection in Venezuela | MARIMAR C.A.',
   desc='MARIMAR C.A. Survey Division: vehicle, cargo and container inspections, draft surveys, on/off-hire and vessel condition surveys at every port in Venezuela. Independent reports for insurance and claims.',
   kicker='Survey Division · All of Venezuela', h1='Marine and cargo surveys at every port in Venezuela',
   lead='We independently verify the condition of vessels, cargo and vehicles at origin and destination. Wherever your cargo is, we inspect it, delivering reliable technical evidence for operations, insurance and claims.',
   svc_t='What we survey',
   services=[('Vehicles', 'VIN-by-VIN records at loading and discharge: damage, missing items, accessories and a standard photo protocol.'),
             ('General and project cargo', 'Condition, quantity and damage. Supervision of loading, discharge, stowage and lashing.'),
             ('Containers', 'Container condition, seals, stuffing and stripping.'),
             ('Draft surveys', 'Determination of cargo loaded or discharged by draft readings.'),
             ('On-hire / off-hire', 'Vessel condition and bunkers on board at delivery and redelivery.'),
             ('Vessel condition and damage', 'Vessel and craft inspections, and damage reports for insurers and claims.')],
   how_t='How we work',
   steps=[('Request', 'Tell us the type of survey, port, cargo and estimated date.'),
          ('On-site inspection', 'Our surveyor records the condition using a standard photo protocol and checklist.'),
          ('Independent report', 'You receive a technical report with evidence for your operation, insurer or claim.')],
   ports_t='Ports where we survey',
   ports_lead='We cover ports and terminals across Venezuela. If your operation is at a port not listed, write to us and we will arrange the survey.',
   why_t='Why an independent survey',
   why=[('Evidence that holds', 'A dated, photographed record made by a third party carries more weight with carriers, ports and insurers.'),
        ('Origin and destination', 'Comparing condition at loading and discharge allows damage to be attributed to the leg where it occurred.'),
        ('Speed', 'Claims have short time limits, so we inspect before cargo leaves the port area.')],
   faq=[['Do you survey at any port in Venezuela?', 'Yes. The Survey Division covers ports and terminals nationwide. We arrange the surveyor\'s travel according to the operation date.'],
        ['Why survey at origin as well?', 'A destination-only survey proves how the cargo arrived, not where it was damaged. With an origin record, damage can be attributed to the transport leg.'],
        ['Is the report valid for insurance claims?', 'Yes. It is an independent technical report with photos and damage descriptions, designed for insurance and claims.'],
        ['How far in advance should I request it?', 'As early as possible, ideally once you know the loading or arrival date, to secure the surveyor\'s attendance.']],
   cta='Request a survey', wa='Hello, I need a survey in Venezuela. Type: … Port: … Cargo: … Date: …',
   nav='Survey', view='View port', survey_in='Survey at'),
}

# Puertos con página de survey propia (fuera de las páginas de puerto del oriente)
SPORTS = [
 {'slug': 'la-guaira', 'lat': 10.6008, 'lon': -66.9331,
  'es': dict(name='La Guaira', region='Estado La Guaira (Caracas)',
     h1='Survey e inspección de carga en el Puerto de La Guaira',
     title='Survey e inspección de vehículos y carga en La Guaira | MARIMAR C.A.',
     desc='Inspección de vehículos, contenedores y carga en el Puerto de La Guaira, principal puerto de la zona de Caracas. Informes independientes para importadores, seguros y reclamos.',
     about='El Puerto de La Guaira, operado por Bolipuertos, es la puerta marítima de Caracas y uno de los principales puertos de importación del país, con movimiento de contenedores, carga general y vehículos.',
     focus=['Inspección de vehículos importados a la descarga', 'Inspección de contenedores y carga general', 'Informes de daños para seguros y reclamos', 'Supervisión de descarga'],
     faq=[['¿Inspeccionan vehículos importados en La Guaira?', 'Sí. Registramos cada unidad por VIN, con croquis de daños y protocolo fotográfico, idealmente antes de que salga del recinto portuario.']]),
  'en': dict(name='La Guaira', region='La Guaira State (Caracas)',
     h1='Marine survey and cargo inspection at the Port of La Guaira',
     title='Vehicle & Cargo Surveys at La Guaira, Venezuela | MARIMAR C.A.',
     desc='Vehicle, container and cargo inspections at the Port of La Guaira, the main port serving Caracas. Independent reports for importers, insurers and claims.',
     about='The Port of La Guaira, operated by Bolipuertos, is Caracas\'s sea gateway and one of the country\'s main import ports, handling containers, general cargo and vehicles.',
     focus=['Discharge surveys of imported vehicles', 'Container and general cargo inspections', 'Damage reports for insurance and claims', 'Discharge supervision'],
     faq=[['Do you survey imported vehicles at La Guaira?', 'Yes. We record each unit by VIN with damage sketches and a photo protocol, ideally before it leaves the port area.']])},
 {'slug': 'puerto-cabello', 'lat': 10.4843, 'lon': -68.0125,
  'es': dict(name='Puerto Cabello', region='Estado Carabobo',
     h1='Survey e inspección de carga en Puerto Cabello',
     title='Survey e inspección de carga y contenedores en Puerto Cabello | MARIMAR C.A.',
     desc='Inspección de contenedores, carga general, vehículos y graneles en Puerto Cabello, estado Carabobo. Informes independientes para operaciones, seguros y reclamos.',
     about='Puerto Cabello, en el estado Carabobo, es el principal puerto comercial de Venezuela por volumen de carga. Opera contenedores, carga general, graneles y vehículos, y está cerca de la refinería El Palito.',
     focus=['Inspección de contenedores y carga general', 'Inspección de vehículos al embarque y a la descarga', 'Draft survey de graneles', 'Informes de daños para seguros y reclamos'],
     faq=[['¿Hacen draft survey en Puerto Cabello?', 'Sí. Determinamos la carga embarcada o descargada por lectura de calados, con informe independiente.']]),
  'en': dict(name='Puerto Cabello', region='Carabobo State',
     h1='Marine survey and cargo inspection at Puerto Cabello',
     title='Cargo & Container Surveys at Puerto Cabello, Venezuela | MARIMAR C.A.',
     desc='Container, general cargo, vehicle and bulk inspections at Puerto Cabello, Carabobo State, Venezuela. Independent reports for operations, insurance and claims.',
     about='Puerto Cabello, in Carabobo State, is Venezuela\'s main commercial port by cargo volume. It handles containers, general cargo, bulk and vehicles, and is close to the El Palito refinery.',
     focus=['Container and general cargo inspections', 'Vehicle surveys at loading and discharge', 'Draft surveys for bulk cargo', 'Damage reports for insurance and claims'],
     faq=[['Do you carry out draft surveys at Puerto Cabello?', 'Yes. We determine cargo loaded or discharged by draft readings, with an independent report.']])},
 {'slug': 'maracaibo', 'lat': 10.6427, 'lon': -71.6125,
  'es': dict(name='Maracaibo', region='Estado Zulia',
     h1='Survey e inspección de carga en Maracaibo',
     title='Survey e inspección de carga en el Puerto de Maracaibo | MARIMAR C.A.',
     desc='Inspección de carga, contenedores y condición de buques en el Puerto de Maracaibo y el Lago de Maracaibo, estado Zulia. Informes independientes para seguros y reclamos.',
     about='El Puerto de Maracaibo, en el estado Zulia y operado por Bolipuertos, atiende carga general, contenedores y graneles del occidente del país. El Lago de Maracaibo concentra además actividad petrolera y embarcaciones de apoyo.',
     focus=['Inspección de carga general y contenedores', 'Condition survey de buques y embarcaciones de apoyo', 'On-hire / off-hire', 'Informes de daños para seguros y reclamos'],
     faq=[['¿Inspeccionan embarcaciones de apoyo en el Lago de Maracaibo?', 'Sí. Hacemos condition surveys y on-hire / off-hire de buques y embarcaciones.']]),
  'en': dict(name='Maracaibo', region='Zulia State',
     h1='Marine survey and cargo inspection in Maracaibo',
     title='Cargo & Vessel Surveys at the Port of Maracaibo, Venezuela | MARIMAR C.A.',
     desc='Cargo, container and vessel condition surveys at the Port of Maracaibo and Lake Maracaibo, Zulia State, Venezuela. Independent reports for insurance and claims.',
     about='The Port of Maracaibo, in Zulia State and operated by Bolipuertos, handles general cargo, containers and bulk for western Venezuela. Lake Maracaibo also concentrates oil activity and support vessels.',
     focus=['General cargo and container inspections', 'Condition surveys of vessels and support craft', 'On-hire / off-hire surveys', 'Damage reports for insurance and claims'],
     faq=[['Do you survey support vessels on Lake Maracaibo?', 'Yes. We carry out condition surveys and on-hire / off-hire surveys of vessels and craft.']])},
 {'slug': 'puerto-ordaz', 'lat': 8.2833, 'lon': -62.7333,
  'es': dict(name='Puerto Ordaz', region='Ciudad Guayana, estado Bolívar · Río Orinoco',
     h1='Survey e inspección de carga en Puerto Ordaz',
     title='Survey e inspección de carga en Puerto Ordaz, río Orinoco | MARIMAR C.A.',
     desc='Inspección de carga de proyecto, equipos pesados y carga general en Puerto Ordaz (Ciudad Guayana), río Orinoco. Supervisión de descarga e informes independientes.',
     about='Puerto Ordaz, en Ciudad Guayana (estado Bolívar), es el polo industrial del río Orinoco. Sus muelles fluviales atienden la industria del hierro, el acero y el aluminio, además de carga de proyecto y equipos pesados para la región.',
     focus=['Supervisión de carga de proyecto y equipos pesados', 'Inspección de condición a la descarga', 'Supervisión de estiba y trincaje', 'Informes de daños para seguros y reclamos'],
     faq=[['¿Pueden supervisar la descarga de un equipo pesado en Puerto Ordaz?', 'Sí. Registramos la condición del equipo, supervisamos la maniobra y la estiba, y emitimos un informe independiente.']]),
  'en': dict(name='Puerto Ordaz', region='Ciudad Guayana, Bolívar State · Orinoco River',
     h1='Marine survey and cargo inspection in Puerto Ordaz',
     title='Project Cargo & Cargo Surveys in Puerto Ordaz, Orinoco River | MARIMAR C.A.',
     desc='Project cargo, heavy equipment and general cargo surveys in Puerto Ordaz (Ciudad Guayana) on the Orinoco River, Venezuela. Discharge supervision and independent reports.',
     about='Puerto Ordaz, in Ciudad Guayana (Bolívar State), is the industrial hub of the Orinoco River. Its river berths serve the iron, steel and aluminium industries, as well as project cargo and heavy equipment for the region.',
     focus=['Project cargo and heavy equipment supervision', 'Condition surveys at discharge', 'Stowage and lashing supervision', 'Damage reports for insurance and claims'],
     faq=[['Can you supervise heavy equipment discharge in Puerto Ordaz?', 'Yes. We record the equipment\'s condition, supervise lifting and stowage, and issue an independent report.']])},
 {'slug': 'paraguana', 'lat': 11.7000, 'lon': -70.2000,
  'es': dict(name='Paraguaná (Punta Cardón y Amuay)', region='Península de Paraguaná, estado Falcón',
     h1='Survey marítimo en Paraguaná: Punta Cardón y Amuay',
     title='Survey marítimo en Paraguaná: Punta Cardón y Amuay | MARIMAR C.A.',
     desc='On-hire / off-hire, condition survey e inspecciones de buques tanqueros en Paraguaná (Punta Cardón y Amuay), estado Falcón. Informes independientes.',
     about='La Península de Paraguaná, en el estado Falcón, alberga los terminales de Punta Cardón y Amuay, asociados al complejo refinador de la zona. Recibe principalmente buques tanqueros.',
     focus=['On-hire / off-hire de tanqueros', 'Condition survey de buques', 'Inspección de daños para seguros y reclamos', 'Apoyo al armador durante la escala'],
     faq=[['¿Hacen on-hire / off-hire de tanqueros en Paraguaná?', 'Sí. Registramos la condición del buque y el combustible a bordo al inicio o al término del arriendo.']]),
  'en': dict(name='Paraguaná (Punta Cardón & Amuay)', region='Paraguaná Peninsula, Falcón State',
     h1='Marine surveys in Paraguaná: Punta Cardón and Amuay',
     title='Marine Surveys in Paraguaná: Punta Cardón & Amuay, Venezuela | MARIMAR C.A.',
     desc='On-hire / off-hire, condition and tanker surveys in Paraguaná (Punta Cardón and Amuay), Falcón State, Venezuela. Independent reports.',
     about='The Paraguaná Peninsula, in Falcón State, hosts the Punta Cardón and Amuay terminals linked to the area\'s refining complex. It mainly receives tankers.',
     focus=['On-hire / off-hire surveys of tankers', 'Vessel condition surveys', 'Damage surveys for insurance and claims', 'Owner support during the call'],
     faq=[['Do you carry out on-hire / off-hire surveys of tankers in Paraguaná?', 'Yes. We record vessel condition and bunkers on board at delivery or redelivery.']])},
]
